#!/usr/bin/env bash

rm board*
rm mov.mp4
echo "old files removed"
echo "running model..."
python3 spatial_interaction_model.py
echo "COMPLETE - Modelling"
echo "running movie..."
python3 mov.py
echo "COMPLETE"
